#ifndef __DEFINE_H__
#define __DEFINE_H__

#define CONNECT_USE_IO_NONE 0
#define CONNECT_USE_IO_SELECT 1
#define CONNECT_USE_IO_POLL 2
#define CONNECT_USE_IO_EPOLL 3

#define LOG_LEVEL_DEBUG 0
#define LOG_LEVEL_INFO 1
#define LOG_LEVEL_WARN 2
#define LOG_LEVEL_ERROR 3
#define LOG_LEVEL_FATAL 4

#define CLIENT_SELECT_ROUND_ROBIN 0
#define CLIENT_SELECT_RANDOM 1

#endif